//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public Recetas()
        {
            this.Reservas = new HashSet<Reservas>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int IdReceta { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public int TiempoCoccion { get; set; }
        public string Descripcion { get; set; }
        public string Ingredientes { get; set; }
        public byte Tipo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
